# Generated by Django 4.1.6 on 2024-03-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateField()),
                ('time_field', models.TimeField()),
                ('alert_message', models.TextField()),
            ],
        ),
    ]
