# Generated by Django 4.1.6 on 2024-03-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerts',
            old_name='date_field',
            new_name='alert_date',
        ),
        migrations.RenameField(
            model_name='alerts',
            old_name='time_field',
            new_name='alert_time',
        ),
    ]
